[workspace]
resolver = "2"
members = ["crates/vole-proto", "crates/vole-sys", "crates/vole-core", "crates/vole-cli", "conformance"]

[workspace.package]
version = "2.8.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/wukongnotnull/vole"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
