#!/usr/bin/env bash
# 从 mole app_protection_data.sh 生成 data/protection.toml
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/third_party/mole-1.48.1/lib/core/app_protection_data.sh"
OUT="$ROOT/data/protection.toml"

export SRC OUT
python3 << 'PY'
import os
import re
from pathlib import Path

src = Path(os.environ["SRC"]).read_text()
out = Path(os.environ["OUT"])

def extract_array(name: str) -> list[str]:
    lines = src.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith(f"readonly {name}=("):
            start = i + 1
            break
    if start is None:
        raise SystemExit(f"missing array {name}")
    items = []
    for line in lines[start:]:
        if line.strip() == ")":
            break
        m = re.match(r'\s*"([^"]*)"', line)
        if m:
            items.append(m.group(1))
    return items

system = extract_array("SYSTEM_CRITICAL_BUNDLES")
data = extract_array("DATA_PROTECTED_BUNDLES")
apple = extract_array("APPLE_UNINSTALLABLE_APPS")
official = extract_array("OFFICIAL_UNINSTALLER_RULES")

out.parent.mkdir(parents=True, exist_ok=True)

def toml_array(key: str, values: list[str]) -> str:
    lines = [f"{key} = ["]
    for v in values:
        lines.append(f"  {v!r},")
    lines.append("]")
    return "\n".join(lines)

body = (
    "# Generated by scripts/gen-protection-toml.sh — do not edit by hand.\n"
    "# Source: third_party/mole-1.48.1/lib/core/app_protection_data.sh\n\n"
    + toml_array("system_critical_bundles", system)
    + "\n\n"
    + toml_array("data_protected_bundles", data)
    + "\n\n"
    + toml_array("apple_uninstallable_apps", apple)
    + "\n\n"
    + toml_array("official_uninstaller_rules", official)
    + "\n"
)
out.write_text(body)
print(
    f"wrote {out} ({len(system)} system + {len(data)} data + "
    f"{len(apple)} apple_uninstallable + {len(official)} official_uninstaller)"
)
PY
